### ISSUE TITLE
Improve demo

### ISSUE THREAD

**Issue by mcg-web** [overblog/GraphQLBundleDemo#1]
# TODO

- [ ] Add a schema using Yaml configuration definition
- [ ] Add a schema using Xml configuration definition
- [ ] Add dataloader (solve n+1)
- [ ] Add an upload example
- [ ] Add a mutation example

**Comment by eman1986** [comment]
if I could add another item, could we also look into adding an example to using mutation?

**Comment by mcg-web** [comment]
Thank you @eman1986 I'm also adding this to todo list :+1:

**Comment by renatomefi** [comment]
Hey @mcg-web nice initiative! :)
I have a few things from a workshop: https://github.com/renatomefi/-overblog-GraphQLBundle-Workshop
So I was thinking how to make it awesome, and I thought of a few things:
- Each commit (or PR) could have a perfect example for one thing, this could later be linked to each part of the documentation
- A lot of comments referencing to the docs (so it's both ways)
- Have this application with certain cpu load, thus could be used for benchmarking
- Also maybe some performance things

Wdyt?

**Comment by mcg-web** [comment]
Hey @renatomefi yes I think these are the best way to process in fact. I'll do separate issues for each TODO.
